### ISSUE TITLE
UI Enhancement

### ISSUE THREAD

**Issue by cla6shade** [ApptiveDev/apptive-home-frontend#25]
## Description

스크롤바 디자인, 인터랙션 등 UI/UX 개선이 필요합니다.

## To-Do
- [x] 스크롤바 디자인 변경
- [x] 요소에 애니메이션 적용 (아래에서 위로 올라오는 등)
- [x] 헤더 메뉴 클릭 시 해당하는 섹션으로 이동하도록 구현

## ETC

해당 이슈는 이전에 저희끼리 토의한 대로, development/ui-enhancement에서 feature 브랜치를 분기하여 개발해봅시다!

**Comment by cla6shade** [comment]
## 추가적으로 할 일

- [ ] .png를 차세대 이미지 파일 형식으로 압축(.webp)
- [ ] 기타 에셋 최적화
